; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -passes=inline -S -o - %s | FileCheck %s

; "stack-protector-layout-only" is a property of the caller: it is neither
; propagated from an inlined callee nor removed when a callee without it is
; inlined, while the ssp/sspstrong/sspreq level is still merged as usual.

declare void @sink()

define internal void @callee_nossp() alwaysinline {
  call void @sink()
  ret void
}

define internal void @callee_sspstrong() sspstrong alwaysinline {
  call void @sink()
  ret void
}

define internal void @callee_ssp_layout_only() ssp "stack-protector-layout-only" alwaysinline {
  call void @sink()
  ret void
}

define internal void @callee_sspreq_layout_only() sspreq "stack-protector-layout-only" alwaysinline {
  call void @sink()
  ret void
}

define internal void @callee_sspstrong_layout_only() sspstrong "stack-protector-layout-only" alwaysinline {
  call void @sink()
  ret void
}

define void @caller_ssp_layout_only_callee_sspstrong() ssp "stack-protector-layout-only" {
; CHECK-LABEL: define void @caller_ssp_layout_only_callee_sspstrong(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    call void @sink()
; CHECK-NEXT:    ret void
;
  call void @callee_sspstrong()
  ret void
}

define void @caller_sspstrong_callee_ssp_layout_only() sspstrong {
; CHECK-LABEL: define void @caller_sspstrong_callee_ssp_layout_only(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    call void @sink()
; CHECK-NEXT:    ret void
;
  call void @callee_ssp_layout_only()
  ret void
}

define void @caller_ssp_callee_sspreq_layout_only() ssp {
; CHECK-LABEL: define void @caller_ssp_callee_sspreq_layout_only(
; CHECK-SAME: ) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    call void @sink()
; CHECK-NEXT:    ret void
;
  call void @callee_sspreq_layout_only()
  ret void
}

define void @caller_nossp_callee_sspstrong_layout_only() {
; CHECK-LABEL: define void @caller_nossp_callee_sspstrong_layout_only() {
; CHECK-NEXT:    call void @sink()
; CHECK-NEXT:    ret void
;
  call void @callee_sspstrong_layout_only()
  ret void
}

define void @caller_sspreq_layout_only_callee_nossp() sspreq "stack-protector-layout-only" {
; CHECK-LABEL: define void @caller_sspreq_layout_only_callee_nossp(
; CHECK-SAME: ) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    call void @sink()
; CHECK-NEXT:    ret void
;
  call void @callee_nossp()
  ret void
}
;.
; CHECK: attributes #[[ATTR0]] = { sspstrong "stack-protector-layout-only" }
; CHECK: attributes #[[ATTR1]] = { sspstrong }
; CHECK: attributes #[[ATTR2]] = { sspreq }
; CHECK: attributes #[[ATTR3]] = { sspreq "stack-protector-layout-only" }
;.
