; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; REQUIRES: x86-registered-target
; RUN: opt -mtriple=x86_64-pc-linux-gnu -passes='require<libcall-lowering-info>,stack-protector' -S -o - %s | FileCheck %s

; Functions with "stack-protector-layout-only" are left untouched: no guard
; slot, no llvm.stackprotector and no __stack_chk_fail call are inserted.

declare void @use(ptr)

define void @layout_only_strong() sspstrong "stack-protector-layout-only" {
; CHECK-LABEL: define void @layout_only_strong(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @use(ptr [[BUF]])
; CHECK-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @use(ptr %buf)
  ret void
}

define void @layout_only_req() sspreq "stack-protector-layout-only" {
; CHECK-LABEL: define void @layout_only_req(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @cookie() sspstrong {
; CHECK-LABEL: define void @cookie(
; CHECK-SAME: ) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[STACKGUARDSLOT:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[STACKGUARD:%.*]] = load volatile ptr, ptr addrspace(257) inttoptr (i32 40 to ptr addrspace(257)), align 8
; CHECK-NEXT:    call void @llvm.stackprotector(ptr [[STACKGUARD]], ptr [[STACKGUARDSLOT]])
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @use(ptr [[BUF]])
; CHECK-NEXT:    [[STACKGUARD1:%.*]] = load volatile ptr, ptr addrspace(257) inttoptr (i32 40 to ptr addrspace(257)), align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load volatile ptr, ptr [[STACKGUARDSLOT]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[STACKGUARD1]], [[TMP1]]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[SP_RETURN:.*]], label %[[CALLSTACKCHECKFAILBLK:.*]], !prof [[PROF0:![0-9]+]]
; CHECK:       [[SP_RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[CALLSTACKCHECKFAILBLK]]:
; CHECK-NEXT:    call void @__stack_chk_fail() #[[ATTR4:[0-9]+]]
; CHECK-NEXT:    unreachable
;
  %buf = alloca [16 x i8], align 1
  call void @use(ptr %buf)
  ret void
}
;.
; CHECK: attributes #[[ATTR0]] = { sspstrong "stack-protector-layout-only" }
; CHECK: attributes #[[ATTR1]] = { sspreq "stack-protector-layout-only" }
; CHECK: attributes #[[ATTR2]] = { sspstrong }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { nocallback nofree nosync nounwind willreturn }
; CHECK: attributes #[[ATTR4]] = { noreturn }
;.
; CHECK: [[PROF0]] = !{!"branch_weights", i32 2147481600, i32 2048}
;.
