; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
;; StackProtector inserts no __stack_chk_fail call for functions with
;; "stack-protector-layout-only", so it must not require
;; LibcallLoweringModuleAnalysis for them.
; REQUIRES: x86-registered-target
; RUN: opt -mtriple=x86_64-- -passes=stack-protector -S -o - %s | FileCheck %s

define void @empty() sspreq "stack-protector-layout-only" {
; CHECK-LABEL: define void @empty(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}
;.
; CHECK: attributes #[[ATTR0]] = { sspreq "stack-protector-layout-only" }
;.
