; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -o - %s | FileCheck %s

; Check that no stack protector is emitted for functions with
; "stack-protector-layout-only".

declare void @use(ptr, ptr, ptr)
declare void @sink(i32)

define void @layout_strong(i32 %n) sspstrong "stack-protector-layout-only" {
; CHECK-LABEL: layout_strong:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    sw a0, 4(sp)
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    addi a1, sp, 12
; CHECK-NEXT:    addi a2, sp, 8
; CHECK-NEXT:    call use
; CHECK-NEXT:    lw a0, 4(sp)
; CHECK-NEXT:    call sink
; CHECK-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 48
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @layout_ssp(i32 %n) ssp "stack-protector-layout-only" {
; CHECK-LABEL: layout_ssp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    sw a0, 12(sp)
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    addi a1, sp, 4
; CHECK-NEXT:    addi a2, sp, 8
; CHECK-NEXT:    call use
; CHECK-NEXT:    lw a0, 12(sp)
; CHECK-NEXT:    call sink
; CHECK-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 48
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @req_empty() sspreq "stack-protector-layout-only" {
; CHECK-LABEL: req_empty:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  ret void
}

define void @cookie(i32 %n) sspstrong {
; CHECK-LABEL: cookie:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s0, 48(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    .cfi_remember_state
; CHECK-NEXT:    lui s0, %hi(__stack_chk_guard)
; CHECK-NEXT:    ld a1, %lo(__stack_chk_guard)(s0)
; CHECK-NEXT:    sd a1, 40(sp)
; CHECK-NEXT:    sw a0, 4(sp)
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    addi a1, sp, 12
; CHECK-NEXT:    addi a2, sp, 8
; CHECK-NEXT:    call use
; CHECK-NEXT:    lw a0, 4(sp)
; CHECK-NEXT:    call sink
; CHECK-NEXT:    ld a0, %lo(__stack_chk_guard)(s0)
; CHECK-NEXT:    ld a1, 40(sp)
; CHECK-NEXT:    bne a0, a1, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s0, 48(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    .cfi_restore_state
; CHECK-NEXT:    call __stack_chk_fail
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}
