; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -stack-symbol-ordering=0 -o - %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -stack-symbol-ordering=0 -O0 -o - %s | FileCheck %s --check-prefix=O0

; For layout-only functions only the stack protector layout is applied; no
; __stack_chk_guard load, store, check or __stack_chk_fail call is inserted.

declare void @use(ptr, ptr, ptr)
declare void @sink(i32)

define void @layout_strong(i32 %n) sspstrong "stack-protector-layout-only" {
; OPT-LABEL: layout_strong:
; OPT:       // %bb.0:
; OPT-NEXT:    sub sp, sp, #48
; OPT-NEXT:    str x30, [sp, #32] // 8-byte Spill
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    .cfi_offset w30, -16
; OPT-NEXT:    str w0, [sp, #4]
; OPT-NEXT:    add x0, sp, #16
; OPT-NEXT:    add x1, sp, #12
; OPT-NEXT:    add x2, sp, #8
; OPT-NEXT:    bl use
; OPT-NEXT:    ldr w0, [sp, #4]
; OPT-NEXT:    bl sink
; OPT-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; OPT-NEXT:    add sp, sp, #48
; OPT-NEXT:    ret
;
; O0-LABEL: layout_strong:
; O0:       // %bb.0:
; O0-NEXT:    sub sp, sp, #48
; O0-NEXT:    str x30, [sp, #32] // 8-byte Spill
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    .cfi_offset w30, -16
; O0-NEXT:    str w0, [sp, #4]
; O0-NEXT:    add x0, sp, #16
; O0-NEXT:    add x1, sp, #12
; O0-NEXT:    add x2, sp, #8
; O0-NEXT:    bl use
; O0-NEXT:    ldr w0, [sp, #4]
; O0-NEXT:    bl sink
; O0-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; O0-NEXT:    add sp, sp, #48
; O0-NEXT:    ret
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @layout_ssp(i32 %n) ssp "stack-protector-layout-only" {
; OPT-LABEL: layout_ssp:
; OPT:       // %bb.0:
; OPT-NEXT:    sub sp, sp, #48
; OPT-NEXT:    str x30, [sp, #32] // 8-byte Spill
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    .cfi_offset w30, -16
; OPT-NEXT:    str w0, [sp, #12]
; OPT-NEXT:    add x0, sp, #16
; OPT-NEXT:    add x1, sp, #4
; OPT-NEXT:    add x2, sp, #8
; OPT-NEXT:    bl use
; OPT-NEXT:    ldr w0, [sp, #12]
; OPT-NEXT:    bl sink
; OPT-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; OPT-NEXT:    add sp, sp, #48
; OPT-NEXT:    ret
;
; O0-LABEL: layout_ssp:
; O0:       // %bb.0:
; O0-NEXT:    sub sp, sp, #48
; O0-NEXT:    str x30, [sp, #32] // 8-byte Spill
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    .cfi_offset w30, -16
; O0-NEXT:    str w0, [sp, #12]
; O0-NEXT:    add x0, sp, #16
; O0-NEXT:    add x1, sp, #4
; O0-NEXT:    add x2, sp, #8
; O0-NEXT:    bl use
; O0-NEXT:    ldr w0, [sp, #12]
; O0-NEXT:    bl sink
; O0-NEXT:    ldr x30, [sp, #32] // 8-byte Reload
; O0-NEXT:    add sp, sp, #48
; O0-NEXT:    ret
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @req_empty() sspreq "stack-protector-layout-only" {
; OPT-LABEL: req_empty:
; OPT:       // %bb.0:
; OPT-NEXT:    ret
;
; O0-LABEL: req_empty:
; O0:       // %bb.0:
; O0-NEXT:    ret
  ret void
}

define void @cookie(i32 %n) sspstrong {
; OPT-LABEL: cookie:
; OPT:       // %bb.0:
; OPT-NEXT:    sub sp, sp, #64
; OPT-NEXT:    str x30, [sp, #48] // 8-byte Spill
; OPT-NEXT:    .cfi_def_cfa_offset 64
; OPT-NEXT:    .cfi_offset w30, -16
; OPT-NEXT:    adrp x8, __stack_chk_guard
; OPT-NEXT:    add x1, sp, #12
; OPT-NEXT:    add x2, sp, #8
; OPT-NEXT:    ldr x8, [x8, :lo12:__stack_chk_guard]
; OPT-NEXT:    str x8, [sp, #40]
; OPT-NEXT:    str w0, [sp, #4]
; OPT-NEXT:    add x0, sp, #16
; OPT-NEXT:    bl use
; OPT-NEXT:    ldr w0, [sp, #4]
; OPT-NEXT:    bl sink
; OPT-NEXT:    adrp x8, __stack_chk_guard
; OPT-NEXT:    ldr x9, [sp, #40]
; OPT-NEXT:    ldr x8, [x8, :lo12:__stack_chk_guard]
; OPT-NEXT:    cmp x8, x9
; OPT-NEXT:    b.ne .LBB3_2
; OPT-NEXT:  // %bb.1:
; OPT-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; OPT-NEXT:    add sp, sp, #64
; OPT-NEXT:    ret
; OPT-NEXT:  .LBB3_2:
; OPT-NEXT:    bl __stack_chk_fail
;
; O0-LABEL: cookie:
; O0:       // %bb.0:
; O0-NEXT:    sub sp, sp, #64
; O0-NEXT:    str x30, [sp, #48] // 8-byte Spill
; O0-NEXT:    .cfi_def_cfa_offset 64
; O0-NEXT:    .cfi_offset w30, -16
; O0-NEXT:    adrp x8, __stack_chk_guard
; O0-NEXT:    ldr x8, [x8, :lo12:__stack_chk_guard]
; O0-NEXT:    str x8, [sp, #40]
; O0-NEXT:    str w0, [sp, #4]
; O0-NEXT:    add x0, sp, #16
; O0-NEXT:    add x1, sp, #12
; O0-NEXT:    add x2, sp, #8
; O0-NEXT:    bl use
; O0-NEXT:    ldr w0, [sp, #4]
; O0-NEXT:    bl sink
; O0-NEXT:    ldr x9, [sp, #40]
; O0-NEXT:    adrp x8, __stack_chk_guard
; O0-NEXT:    ldr x8, [x8, :lo12:__stack_chk_guard]
; O0-NEXT:    subs x8, x8, x9
; O0-NEXT:    b.ne .LBB3_1
; O0-NEXT:    b .LBB3_2
; O0-NEXT:  .LBB3_1:
; O0-NEXT:    bl __stack_chk_fail
; O0-NEXT:  .LBB3_2:
; O0-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; O0-NEXT:    add sp, sp, #64
; O0-NEXT:    ret
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}
