; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -stack-symbol-ordering=0 -o - %s | FileCheck %s --check-prefix=OPT
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -stack-symbol-ordering=0 -O0 -o - %s | FileCheck %s --check-prefix=O0

; For layout-only functions only the stack protector layout is applied; no
; guard load, store, check or __stack_chk_fail call is inserted.

declare void @use(ptr, ptr, ptr)
declare void @sink(i32)

define void @layout_strong(i32 %n) sspstrong "stack-protector-layout-only" {
; OPT-LABEL: layout_strong:
; OPT:       # %bb.0:
; OPT-NEXT:    subq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; OPT-NEXT:    callq use@PLT
; OPT-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; OPT-NEXT:    callq sink@PLT
; OPT-NEXT:    addq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 8
; OPT-NEXT:    retq
;
; O0-LABEL: layout_strong:
; O0:       # %bb.0:
; O0-NEXT:    subq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; O0-NEXT:    callq use@PLT
; O0-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; O0-NEXT:    callq sink@PLT
; O0-NEXT:    addq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 8
; O0-NEXT:    retq
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @layout_ssp(i32 %n) ssp "stack-protector-layout-only" {
; OPT-LABEL: layout_ssp:
; OPT:       # %bb.0:
; OPT-NEXT:    subq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; OPT-NEXT:    callq use@PLT
; OPT-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; OPT-NEXT:    callq sink@PLT
; OPT-NEXT:    addq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 8
; OPT-NEXT:    retq
;
; O0-LABEL: layout_ssp:
; O0:       # %bb.0:
; O0-NEXT:    subq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; O0-NEXT:    callq use@PLT
; O0-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; O0-NEXT:    callq sink@PLT
; O0-NEXT:    addq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 8
; O0-NEXT:    retq
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}

define void @req_empty() sspreq "stack-protector-layout-only" {
; OPT-LABEL: req_empty:
; OPT:       # %bb.0:
; OPT-NEXT:    retq
;
; O0-LABEL: req_empty:
; O0:       # %bb.0:
; O0-NEXT:    retq
  ret void
}

define void @cookie(i32 %n) sspstrong {
; OPT-LABEL: cookie:
; OPT:       # %bb.0:
; OPT-NEXT:    subq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    movq %fs:40, %rax
; OPT-NEXT:    movq %rax, {{[0-9]+}}(%rsp)
; OPT-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; OPT-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; OPT-NEXT:    callq use@PLT
; OPT-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; OPT-NEXT:    callq sink@PLT
; OPT-NEXT:    movq %fs:40, %rax
; OPT-NEXT:    cmpq {{[0-9]+}}(%rsp), %rax
; OPT-NEXT:    jne .LBB3_2
; OPT-NEXT:  # %bb.1: # %SP_return
; OPT-NEXT:    addq $40, %rsp
; OPT-NEXT:    .cfi_def_cfa_offset 8
; OPT-NEXT:    retq
; OPT-NEXT:  .LBB3_2: # %CallStackCheckFailBlk
; OPT-NEXT:    .cfi_def_cfa_offset 48
; OPT-NEXT:    callq __stack_chk_fail@PLT
;
; O0-LABEL: cookie:
; O0:       # %bb.0:
; O0-NEXT:    subq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    movq %fs:40, %rax
; O0-NEXT:    movq %rax, {{[0-9]+}}(%rsp)
; O0-NEXT:    movl %edi, {{[0-9]+}}(%rsp)
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; O0-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; O0-NEXT:    callq use@PLT
; O0-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; O0-NEXT:    callq sink@PLT
; O0-NEXT:    movq %fs:40, %rax
; O0-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; O0-NEXT:    cmpq %rcx, %rax
; O0-NEXT:    jne .LBB3_2
; O0-NEXT:  # %bb.1: # %SP_return
; O0-NEXT:    addq $40, %rsp
; O0-NEXT:    .cfi_def_cfa_offset 8
; O0-NEXT:    retq
; O0-NEXT:  .LBB3_2: # %CallStackCheckFailBlk
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    callq __stack_chk_fail@PLT
  %scalar = alloca i32, align 4
  %addrof = alloca i32, align 4
  %small = alloca [4 x i8], align 4
  %large = alloca [16 x i8], align 16
  store i32 %n, ptr %scalar
  call void @use(ptr %large, ptr %small, ptr %addrof)
  %v = load i32, ptr %scalar
  call void @sink(i32 %v)
  ret void
}
